// ─── IPL Auction — In-memory data store with 130 players ───────────────────────────────────────

const players = [
  // Elite Players (1-40) - 2.00 Cr
  { id: 1, name: "Virat Kohli", role: "Batsman", country: "India", base_price: 2.00, age: 36, stat1: 98, stat1_label: "Rating", stat2: 237, stat2_label: "Matches", stat3: 36.2, stat3_label: "Avg", prev_team: "RCB", status: "pending" },
  { id: 2, name: "Rohit Sharma", role: "Batsman", country: "India", base_price: 2.00, age: 37, stat1: 97, stat1_label: "Rating", stat2: 243, stat2_label: "Matches", stat3: 30.3, stat3_label: "Avg", prev_team: "MI", status: "pending" },
  { id: 3, name: "MS Dhoni", role: "Wicketkeeper", country: "India", base_price: 2.00, age: 43, stat1: 96, stat1_label: "Rating", stat2: 250, stat2_label: "Matches", stat3: 38.8, stat3_label: "Avg", prev_team: "CSK", status: "pending" },
  { id: 4, name: "Jasprit Bumrah", role: "Bowler", country: "India", base_price: 2.00, age: 31, stat1: 97, stat1_label: "Rating", stat2: 133, stat2_label: "Matches", stat3: 7.30, stat3_label: "Economy", prev_team: "MI", status: "pending" },
  { id: 5, name: "Hardik Pandya", role: "All-rounder", country: "India", base_price: 2.00, age: 31, stat1: 96, stat1_label: "Rating", stat2: 123, stat2_label: "Matches", stat3: 29.8, stat3_label: "SR/10", prev_team: "MI", status: "pending" },
  { id: 6, name: "AB de Villiers", role: "Batsman", country: "SA", base_price: 2.00, age: 40, stat1: 98, stat1_label: "Rating", stat2: 184, stat2_label: "Matches", stat3: 39.7, stat3_label: "Avg", prev_team: "RCB", status: "pending" },
  { id: 7, name: "Chris Gayle", role: "Batsman", country: "WI", base_price: 2.00, age: 45, stat1: 97, stat1_label: "Rating", stat2: 142, stat2_label: "Matches", stat3: 39.7, stat3_label: "Avg", prev_team: "PBKS", status: "pending" },
  { id: 8, name: "Jos Buttler", role: "Wicketkeeper", country: "England", base_price: 2.00, age: 34, stat1: 96, stat1_label: "Rating", stat2: 96, stat2_label: "Matches", stat3: 37.9, stat3_label: "Avg", prev_team: "RR", status: "pending" },
  { id: 9, name: "Ben Stokes", role: "All-rounder", country: "England", base_price: 2.00, age: 33, stat1: 96, stat1_label: "Rating", stat2: 43, stat2_label: "Matches", stat3: 32.5, stat3_label: "Avg", prev_team: "CSK", status: "pending" },
  { id: 10, name: "Rashid Khan", role: "Bowler", country: "AFG", base_price: 2.00, age: 26, stat1: 97, stat1_label: "Rating", stat2: 109, stat2_label: "Matches", stat3: 6.67, stat3_label: "Economy", prev_team: "GT", status: "pending" },
  { id: 11, name: "KL Rahul", role: "Wicketkeeper", country: "India", base_price: 2.00, age: 32, stat1: 95, stat1_label: "Rating", stat2: 115, stat2_label: "Matches", stat3: 46.8, stat3_label: "Avg", prev_team: "LSG", status: "pending" },
  { id: 12, name: "Shubman Gill", role: "Batsman", country: "India", base_price: 2.00, age: 25, stat1: 95, stat1_label: "Rating", stat2: 91, stat2_label: "Matches", stat3: 38.4, stat3_label: "Avg", prev_team: "GT", status: "pending" },
  { id: 13, name: "Suryakumar Yadav", role: "Batsman", country: "India", base_price: 2.00, age: 34, stat1: 96, stat1_label: "Rating", stat2: 139, stat2_label: "Matches", stat3: 31.8, stat3_label: "Avg", prev_team: "MI", status: "pending" },
  { id: 14, name: "David Warner", role: "Batsman", country: "Australia", base_price: 2.00, age: 38, stat1: 95, stat1_label: "Rating", stat2: 176, stat2_label: "Matches", stat3: 41.2, stat3_label: "Avg", prev_team: "DC", status: "pending" },
  { id: 15, name: "Glenn Maxwell", role: "All-rounder", country: "Australia", base_price: 2.00, age: 36, stat1: 95, stat1_label: "Rating", stat2: 124, stat2_label: "Matches", stat3: 27.5, stat3_label: "Avg", prev_team: "RCB", status: "pending" },
  { id: 16, name: "Andre Russell", role: "All-rounder", country: "WI", base_price: 2.00, age: 36, stat1: 96, stat1_label: "Rating", stat2: 112, stat2_label: "Matches", stat3: 30.2, stat3_label: "Avg", prev_team: "KKR", status: "pending" },
  { id: 17, name: "Kane Williamson", role: "Batsman", country: "NZ", base_price: 2.00, age: 34, stat1: 95, stat1_label: "Rating", stat2: 77, stat2_label: "Matches", stat3: 36.2, stat3_label: "Avg", prev_team: "GT", status: "pending" },
  { id: 18, name: "Faf du Plessis", role: "Batsman", country: "SA", base_price: 2.00, age: 40, stat1: 94, stat1_label: "Rating", stat2: 130, stat2_label: "Matches", stat3: 36.9, stat3_label: "Avg", prev_team: "RCB", status: "pending" },
  { id: 19, name: "Quinton de Kock", role: "Wicketkeeper", country: "SA", base_price: 2.00, age: 32, stat1: 95, stat1_label: "Rating", stat2: 96, stat2_label: "Matches", stat3: 32.2, stat3_label: "Avg", prev_team: "LSG", status: "pending" },
  { id: 20, name: "Trent Boult", role: "Bowler", country: "NZ", base_price: 2.00, age: 35, stat1: 94, stat1_label: "Rating", stat2: 88, stat2_label: "Matches", stat3: 8.24, stat3_label: "Economy", prev_team: "RR", status: "pending" },
  { id: 21, name: "Mohammed Shami", role: "Bowler", country: "India", base_price: 2.00, age: 34, stat1: 94, stat1_label: "Rating", stat2: 110, stat2_label: "Matches", stat3: 8.44, stat3_label: "Economy", prev_team: "GT", status: "pending" },
  { id: 22, name: "Bhuvneshwar Kumar", role: "Bowler", country: "India", base_price: 2.00, age: 34, stat1: 94, stat1_label: "Rating", stat2: 160, stat2_label: "Matches", stat3: 7.39, stat3_label: "Economy", prev_team: "SRH", status: "pending" },
  { id: 23, name: "Yuzvendra Chahal", role: "Bowler", country: "India", base_price: 2.00, age: 34, stat1: 95, stat1_label: "Rating", stat2: 145, stat2_label: "Matches", stat3: 7.67, stat3_label: "Economy", prev_team: "RR", status: "pending" },
  { id: 24, name: "Kuldeep Yadav", role: "Bowler", country: "India", base_price: 2.00, age: 30, stat1: 94, stat1_label: "Rating", stat2: 73, stat2_label: "Matches", stat3: 8.13, stat3_label: "Economy", prev_team: "DC", status: "pending" },
  { id: 25, name: "Ravindra Jadeja", role: "All-rounder", country: "India", base_price: 2.00, age: 36, stat1: 96, stat1_label: "Rating", stat2: 226, stat2_label: "Matches", stat3: 26.6, stat3_label: "Avg", prev_team: "CSK", status: "pending" },
  { id: 26, name: "Axar Patel", role: "All-rounder", country: "India", base_price: 2.00, age: 30, stat1: 94, stat1_label: "Rating", stat2: 136, stat2_label: "Matches", stat3: 19.8, stat3_label: "Avg", prev_team: "DC", status: "pending" },
  { id: 27, name: "Ruturaj Gaikwad", role: "Batsman", country: "India", base_price: 2.00, age: 27, stat1: 95, stat1_label: "Rating", stat2: 52, stat2_label: "Matches", stat3: 39.1, stat3_label: "Avg", prev_team: "CSK", status: "pending" },
  { id: 28, name: "Ishan Kishan", role: "Wicketkeeper", country: "India", base_price: 2.00, age: 26, stat1: 94, stat1_label: "Rating", stat2: 91, stat2_label: "Matches", stat3: 29.4, stat3_label: "Avg", prev_team: "MI", status: "pending" },
  { id: 29, name: "Sanju Samson", role: "Wicketkeeper", country: "India", base_price: 2.00, age: 30, stat1: 95, stat1_label: "Rating", stat2: 152, stat2_label: "Matches", stat3: 29.2, stat3_label: "Avg", prev_team: "RR", status: "pending" },
  { id: 30, name: "Nicholas Pooran", role: "Wicketkeeper", country: "WI", base_price: 2.00, age: 29, stat1: 95, stat1_label: "Rating", stat2: 62, stat2_label: "Matches", stat3: 27.9, stat3_label: "Avg", prev_team: "LSG", status: "pending" },
  { id: 31, name: "Marcus Stoinis", role: "All-rounder", country: "Australia", base_price: 2.00, age: 35, stat1: 94, stat1_label: "Rating", stat2: 82, stat2_label: "Matches", stat3: 27.1, stat3_label: "Avg", prev_team: "LSG", status: "pending" },
  { id: 32, name: "Cameron Green", role: "All-rounder", country: "Australia", base_price: 2.00, age: 25, stat1: 94, stat1_label: "Rating", stat2: 16, stat2_label: "Matches", stat3: 50.2, stat3_label: "Avg", prev_team: "RCB", status: "pending" },
  { id: 33, name: "Devon Conway", role: "Batsman", country: "NZ", base_price: 2.00, age: 33, stat1: 95, stat1_label: "Rating", stat2: 22, stat2_label: "Matches", stat3: 48.6, stat3_label: "Avg", prev_team: "CSK", status: "pending" },
  { id: 34, name: "Aiden Markram", role: "All-rounder", country: "SA", base_price: 2.00, age: 30, stat1: 94, stat1_label: "Rating", stat2: 33, stat2_label: "Matches", stat3: 32.7, stat3_label: "Avg", prev_team: "SRH", status: "pending" },
  { id: 35, name: "Heinrich Klaasen", role: "Wicketkeeper", country: "SA", base_price: 2.00, age: 33, stat1: 95, stat1_label: "Rating", stat2: 19, stat2_label: "Matches", stat3: 37.4, stat3_label: "Avg", prev_team: "SRH", status: "pending" },
  { id: 36, name: "Tim David", role: "Batsman", country: "Australia", base_price: 2.00, age: 28, stat1: 94, stat1_label: "Rating", stat2: 25, stat2_label: "Matches", stat3: 29.2, stat3_label: "Avg", prev_team: "MI", status: "pending" },
  { id: 37, name: "Mitchell Starc", role: "Bowler", country: "Australia", base_price: 2.00, age: 34, stat1: 96, stat1_label: "Rating", stat2: 27, stat2_label: "Matches", stat3: 7.17, stat3_label: "Economy", prev_team: "KKR", status: "pending" },
  { id: 38, name: "Pat Cummins", role: "Bowler", country: "Australia", base_price: 2.00, age: 31, stat1: 95, stat1_label: "Rating", stat2: 42, stat2_label: "Matches", stat3: 8.54, stat3_label: "Economy", prev_team: "SRH", status: "pending" },
  { id: 39, name: "Kagiso Rabada", role: "Bowler", country: "SA", base_price: 2.00, age: 29, stat1: 95, stat1_label: "Rating", stat2: 69, stat2_label: "Matches", stat3: 8.35, stat3_label: "Economy", prev_team: "PBKS", status: "pending" },
  { id: 40, name: "Anrich Nortje", role: "Bowler", country: "SA", base_price: 2.00, age: 31, stat1: 94, stat1_label: "Rating", stat2: 40, stat2_label: "Matches", stat3: 8.33, stat3_label: "Economy", prev_team: "DC", status: "pending" },

  // Top Tier Indian (41-55) - 1.50 Cr
  { id: 41, name: "Shikhar Dhawan", role: "Batsman", country: "India", base_price: 1.50, age: 39, stat1: 92, stat1_label: "Rating", stat2: 217, stat2_label: "Matches", stat3: 35.3, stat3_label: "Avg", prev_team: "PBKS", status: "pending" },
  { id: 42, name: "Yashasvi Jaiswal", role: "Batsman", country: "India", base_price: 1.50, age: 23, stat1: 93, stat1_label: "Rating", stat2: 37, stat2_label: "Matches", stat3: 32.6, stat3_label: "Avg", prev_team: "RR", status: "pending" },
  { id: 43, name: "Rinku Singh", role: "Batsman", country: "India", base_price: 1.50, age: 27, stat1: 92, stat1_label: "Rating", stat2: 31, stat2_label: "Matches", stat3: 36.3, stat3_label: "Avg", prev_team: "KKR", status: "pending" },
  { id: 44, name: "Tilak Varma", role: "Batsman", country: "India", base_price: 1.50, age: 22, stat1: 91, stat1_label: "Rating", stat2: 25, stat2_label: "Matches", stat3: 38.9, stat3_label: "Avg", prev_team: "MI", status: "pending" },
  { id: 45, name: "Rahul Tripathi", role: "Batsman", country: "India", base_price: 1.50, age: 33, stat1: 91, stat1_label: "Rating", stat2: 89, stat2_label: "Matches", stat3: 27.5, stat3_label: "Avg", prev_team: "SRH", status: "pending" },
  { id: 46, name: "Sai Sudharsan", role: "Batsman", country: "India", base_price: 1.50, age: 23, stat1: 91, stat1_label: "Rating", stat2: 13, stat2_label: "Matches", stat3: 46.1, stat3_label: "Avg", prev_team: "GT", status: "pending" },
  { id: 47, name: "Rajat Patidar", role: "Batsman", country: "India", base_price: 1.50, age: 31, stat1: 90, stat1_label: "Rating", stat2: 12, stat2_label: "Matches", stat3: 40.4, stat3_label: "Avg", prev_team: "RCB", status: "pending" },
  { id: 48, name: "Shivam Dube", role: "All-rounder", country: "India", base_price: 1.50, age: 31, stat1: 90, stat1_label: "Rating", stat2: 51, stat2_label: "Matches", stat3: 28.1, stat3_label: "Avg", prev_team: "CSK", status: "pending" },
  { id: 49, name: "Arshdeep Singh", role: "Bowler", country: "India", base_price: 1.50, age: 25, stat1: 91, stat1_label: "Rating", stat2: 51, stat2_label: "Matches", stat3: 8.74, stat3_label: "Economy", prev_team: "PBKS", status: "pending" },
  { id: 50, name: "T Natarajan", role: "Bowler", country: "India", base_price: 1.50, age: 33, stat1: 91, stat1_label: "Rating", stat2: 47, stat2_label: "Matches", stat3: 8.77, stat3_label: "Economy", prev_team: "SRH", status: "pending" },
  { id: 51, name: "Varun Chakravarthy", role: "Bowler", country: "India", base_price: 1.50, age: 33, stat1: 90, stat1_label: "Rating", stat2: 56, stat2_label: "Matches", stat3: 7.45, stat3_label: "Economy", prev_team: "KKR", status: "pending" },
  { id: 52, name: "Harshal Patel", role: "Bowler", country: "India", base_price: 1.50, age: 34, stat1: 90, stat1_label: "Rating", stat2: 91, stat2_label: "Matches", stat3: 8.56, stat3_label: "Economy", prev_team: "PBKS", status: "pending" },
  { id: 53, name: "Deepak Chahar", role: "All-rounder", country: "India", base_price: 1.50, age: 32, stat1: 90, stat1_label: "Rating", stat2: 73, stat2_label: "Matches", stat3: 7.89, stat3_label: "Economy", prev_team: "CSK", status: "pending" },
  { id: 54, name: "Umran Malik", role: "Bowler", country: "India", base_price: 1.50, age: 25, stat1: 90, stat1_label: "Rating", stat2: 25, stat2_label: "Matches", stat3: 9.33, stat3_label: "Economy", prev_team: "SRH", status: "pending" },
  { id: 55, name: "Mohammed Siraj", role: "Bowler", country: "India", base_price: 1.50, age: 30, stat1: 93, stat1_label: "Rating", stat2: 79, stat2_label: "Matches", stat3: 8.62, stat3_label: "Economy", prev_team: "RCB", status: "pending" },

  // Mid Tier Indian (56-85) - 1.00 Cr
  { id: 56, name: "Nitish Rana", role: "Batsman", country: "India", base_price: 1.00, age: 31, stat1: 89, stat1_label: "Rating", stat2: 105, stat2_label: "Matches", stat3: 28.5, stat3_label: "Avg", prev_team: "KKR", status: "pending" },
  { id: 57, name: "Mayank Agarwal", role: "Batsman", country: "India", base_price: 1.00, age: 34, stat1: 88, stat1_label: "Rating", stat2: 123, stat2_label: "Matches", stat3: 23.0, stat3_label: "Avg", prev_team: "SRH", status: "pending" },
  { id: 58, name: "Prithvi Shaw", role: "Batsman", country: "India", base_price: 1.00, age: 25, stat1: 88, stat1_label: "Rating", stat2: 71, stat2_label: "Matches", stat3: 23.9, stat3_label: "Avg", prev_team: "DC", status: "pending" },
  { id: 59, name: "Devdutt Padikkal", role: "Batsman", country: "India", base_price: 1.00, age: 24, stat1: 89, stat1_label: "Rating", stat2: 57, stat2_label: "Matches", stat3: 23.1, stat3_label: "Avg", prev_team: "LSG", status: "pending" },
  { id: 60, name: "Shahrukh Khan", role: "All-rounder", country: "India", base_price: 1.00, age: 29, stat1: 89, stat1_label: "Rating", stat2: 33, stat2_label: "Matches", stat3: 20.2, stat3_label: "Avg", prev_team: "GT", status: "pending" },
  { id: 61, name: "Dinesh Karthik", role: "Wicketkeeper", country: "India", base_price: 1.00, age: 39, stat1: 87, stat1_label: "Rating", stat2: 242, stat2_label: "Matches", stat3: 26.6, stat3_label: "Avg", prev_team: "RCB", status: "pending" },
  { id: 62, name: "Wriddhiman Saha", role: "Wicketkeeper", country: "India", base_price: 1.00, age: 40, stat1: 85, stat1_label: "Rating", stat2: 161, stat2_label: "Matches", stat3: 25.1, stat3_label: "Avg", prev_team: "GT", status: "pending" },
  { id: 63, name: "Vijay Shankar", role: "All-rounder", country: "India", base_price: 1.00, age: 34, stat1: 86, stat1_label: "Rating", stat2: 65, stat2_label: "Matches", stat3: 25.1, stat3_label: "Avg", prev_team: "GT", status: "pending" },
  { id: 64, name: "Krunal Pandya", role: "All-rounder", country: "India", base_price: 1.00, age: 34, stat1: 89, stat1_label: "Rating", stat2: 113, stat2_label: "Matches", stat3: 21.3, stat3_label: "Avg", prev_team: "LSG", status: "pending" },
  { id: 65, name: "Avesh Khan", role: "Bowler", country: "India", base_price: 1.00, age: 28, stat1: 89, stat1_label: "Rating", stat2: 47, stat2_label: "Matches", stat3: 8.56, stat3_label: "Economy", prev_team: "RR", status: "pending" },
  { id: 66, name: "Khaleel Ahmed", role: "Bowler", country: "India", base_price: 1.00, age: 27, stat1: 88, stat1_label: "Rating", stat2: 43, stat2_label: "Matches", stat3: 8.55, stat3_label: "Economy", prev_team: "DC", status: "pending" },
  { id: 67, name: "Mukesh Kumar", role: "Bowler", country: "India", base_price: 1.00, age: 31, stat1: 87, stat1_label: "Rating", stat2: 10, stat2_label: "Matches", stat3: 10.5, stat3_label: "Economy", prev_team: "DC", status: "pending" },
  { id: 68, name: "Chetan Sakariya", role: "Bowler", country: "India", base_price: 1.00, age: 26, stat1: 88, stat1_label: "Rating", stat2: 19, stat2_label: "Matches", stat3: 8.50, stat3_label: "Economy", prev_team: "KKR", status: "pending" },
  { id: 69, name: "Rahul Chahar", role: "Bowler", country: "India", base_price: 1.00, age: 25, stat1: 89, stat1_label: "Rating", stat2: 69, stat2_label: "Matches", stat3: 7.51, stat3_label: "Economy", prev_team: "PBKS", status: "pending" },
  { id: 70, name: "Shahbaz Ahmed", role: "All-rounder", country: "India", base_price: 1.00, age: 30, stat1: 87, stat1_label: "Rating", stat2: 39, stat2_label: "Matches", stat3: 18.6, stat3_label: "Avg", prev_team: "SRH", status: "pending" },
  { id: 71, name: "Lalit Yadav", role: "All-rounder", country: "India", base_price: 1.00, age: 28, stat1: 85, stat1_label: "Rating", stat2: 25, stat2_label: "Matches", stat3: 20.3, stat3_label: "Avg", prev_team: "DC", status: "pending" },
  { id: 72, name: "Akash Madhwal", role: "Bowler", country: "India", base_price: 1.00, age: 31, stat1: 88, stat1_label: "Rating", stat2: 8, stat2_label: "Matches", stat3: 8.58, stat3_label: "Economy", prev_team: "MI", status: "pending" },
  { id: 73, name: "Mohsin Khan", role: "Bowler", country: "India", base_price: 1.00, age: 26, stat1: 89, stat1_label: "Rating", stat2: 14, stat2_label: "Matches", stat3: 6.84, stat3_label: "Economy", prev_team: "LSG", status: "pending" },
  { id: 74, name: "Yash Dayal", role: "Bowler", country: "India", base_price: 1.00, age: 27, stat1: 87, stat1_label: "Rating", stat2: 14, stat2_label: "Matches", stat3: 9.38, stat3_label: "Economy", prev_team: "RCB", status: "pending" },
  { id: 75, name: "Sandeep Sharma", role: "Bowler", country: "India", base_price: 1.00, age: 31, stat1: 88, stat1_label: "Rating", stat2: 116, stat2_label: "Matches", stat3: 7.86, stat3_label: "Economy", prev_team: "RR", status: "pending" },
  { id: 76, name: "Riyan Parag", role: "All-rounder", country: "India", base_price: 1.00, age: 23, stat1: 88, stat1_label: "Rating", stat2: 54, stat2_label: "Matches", stat3: 16.2, stat3_label: "Avg", prev_team: "RR", status: "pending" },
  { id: 77, name: "Sarfaraz Khan", role: "Batsman", country: "India", base_price: 1.00, age: 27, stat1: 87, stat1_label: "Rating", stat2: 50, stat2_label: "Matches", stat3: 22.5, stat3_label: "Avg", prev_team: "DC", status: "pending" },
  { id: 78, name: "Anuj Rawat", role: "Wicketkeeper", country: "India", base_price: 1.00, age: 25, stat1: 85, stat1_label: "Rating", stat2: 24, stat2_label: "Matches", stat3: 19.3, stat3_label: "Avg", prev_team: "RCB", status: "pending" },
  { id: 79, name: "Dhruv Jurel", role: "Wicketkeeper", country: "India", base_price: 1.00, age: 24, stat1: 88, stat1_label: "Rating", stat2: 13, stat2_label: "Matches", stat3: 21.5, stat3_label: "Avg", prev_team: "RR", status: "pending" },
  { id: 80, name: "Abhinav Manohar", role: "Batsman", country: "India", base_price: 1.00, age: 30, stat1: 86, stat1_label: "Rating", stat2: 18, stat2_label: "Matches", stat3: 19.8, stat3_label: "Avg", prev_team: "GT", status: "pending" },
  { id: 81, name: "Priyam Garg", role: "Batsman", country: "India", base_price: 1.00, age: 24, stat1: 85, stat1_label: "Rating", stat2: 21, stat2_label: "Matches", stat3: 15.6, stat3_label: "Avg", prev_team: "SRH", status: "pending" },
  { id: 82, name: "Mandeep Singh", role: "Batsman", country: "India", base_price: 1.00, age: 33, stat1: 84, stat1_label: "Rating", stat2: 111, stat2_label: "Matches", stat3: 21.5, stat3_label: "Avg", prev_team: "KKR", status: "pending" },
  { id: 83, name: "Karun Nair", role: "Batsman", country: "India", base_price: 1.00, age: 33, stat1: 85, stat1_label: "Rating", stat2: 76, stat2_label: "Matches", stat3: 23.9, stat3_label: "Avg", prev_team: "LSG", status: "pending" },
  { id: 84, name: "Piyush Chawla", role: "Bowler", country: "India", base_price: 1.00, age: 36, stat1: 86, stat1_label: "Rating", stat2: 181, stat2_label: "Matches", stat3: 7.91, stat3_label: "Economy", prev_team: "MI", status: "pending" },
  { id: 85, name: "Amit Mishra", role: "Bowler", country: "India", base_price: 1.00, age: 42, stat1: 84, stat1_label: "Rating", stat2: 161, stat2_label: "Matches", stat3: 7.38, stat3_label: "Economy", prev_team: "LSG", status: "pending" },

  // Budget Tier (86-110) - 0.75 Cr
  { id: 86, name: "Jayant Yadav", role: "All-rounder", country: "India", base_price: 0.75, age: 35, stat1: 83, stat1_label: "Rating", stat2: 19, stat2_label: "Matches", stat3: 7.15, stat3_label: "Economy", prev_team: "GT", status: "pending" },
  { id: 87, name: "KS Bharat", role: "Wicketkeeper", country: "India", base_price: 0.75, age: 31, stat1: 84, stat1_label: "Rating", stat2: 10, stat2_label: "Matches", stat3: 24.5, stat3_label: "Avg", prev_team: "KKR", status: "pending" },
  { id: 88, name: "Manish Pandey", role: "Batsman", country: "India", base_price: 0.75, age: 35, stat1: 87, stat1_label: "Rating", stat2: 170, stat2_label: "Matches", stat3: 29.8, stat3_label: "Avg", prev_team: "KKR", status: "pending" },
  { id: 89, name: "Washington Sundar", role: "All-rounder", country: "India", base_price: 0.75, age: 25, stat1: 88, stat1_label: "Rating", stat2: 60, stat2_label: "Matches", stat3: 7.54, stat3_label: "Economy", prev_team: "SRH", status: "pending" },
  { id: 90, name: "Shardul Thakur", role: "All-rounder", country: "India", base_price: 0.75, age: 33, stat1: 89, stat1_label: "Rating", stat2: 86, stat2_label: "Matches", stat3: 9.21, stat3_label: "Economy", prev_team: "CSK", status: "pending" },
  { id: 91, name: "Navdeep Saini", role: "Bowler", country: "India", base_price: 0.75, age: 32, stat1: 86, stat1_label: "Rating", stat2: 32, stat2_label: "Matches", stat3: 8.94, stat3_label: "Economy", prev_team: "RR", status: "pending" },
  { id: 92, name: "Kuldip Yadav (domestic)", role: "Bowler", country: "India", base_price: 0.75, age: 28, stat1: 82, stat1_label: "Rating", stat2: 5, stat2_label: "Matches", stat3: 9.10, stat3_label: "Economy", prev_team: "Domestic", status: "pending" },
  { id: 93, name: "Ravi Bishnoi", role: "Bowler", country: "India", base_price: 0.75, age: 24, stat1: 90, stat1_label: "Rating", stat2: 52, stat2_label: "Matches", stat3: 7.53, stat3_label: "Economy", prev_team: "LSG", status: "pending" },
  { id: 94, name: "Ishan Porel", role: "Bowler", country: "India", base_price: 0.75, age: 26, stat1: 80, stat1_label: "Rating", stat2: 1, stat2_label: "Matches", stat3: 11.2, stat3_label: "Economy", prev_team: "PBKS", status: "pending" },
  { id: 95, name: "Kartik Tyagi", role: "Bowler", country: "India", base_price: 0.75, age: 24, stat1: 82, stat1_label: "Rating", stat2: 19, stat2_label: "Matches", stat3: 10.1, stat3_label: "Economy", prev_team: "GT", status: "pending" },
  { id: 96, name: "Shivam Mavi", role: "Bowler", country: "India", base_price: 0.75, age: 26, stat1: 83, stat1_label: "Rating", stat2: 32, stat2_label: "Matches", stat3: 8.71, stat3_label: "Economy", prev_team: "LSG", status: "pending" },
  { id: 97, name: "Kamlesh Nagarkoti", role: "Bowler", country: "India", base_price: 0.75, age: 25, stat1: 82, stat1_label: "Rating", stat2: 12, stat2_label: "Matches", stat3: 9.50, stat3_label: "Economy", prev_team: "DC", status: "pending" },
  { id: 98, name: "Rahul Tewatia", role: "All-rounder", country: "India", base_price: 0.75, age: 31, stat1: 89, stat1_label: "Rating", stat2: 81, stat2_label: "Matches", stat3: 25.1, stat3_label: "Avg", prev_team: "GT", status: "pending" },
  { id: 99, name: "Abhishek Sharma", role: "All-rounder", country: "India", base_price: 0.75, age: 24, stat1: 89, stat1_label: "Rating", stat2: 47, stat2_label: "Matches", stat3: 23.1, stat3_label: "Avg", prev_team: "SRH", status: "pending" },
  { id: 100, name: "Tilak Raj (domestic)", role: "Batsman", country: "India", base_price: 0.75, age: 28, stat1: 78, stat1_label: "Rating", stat2: 0, stat2_label: "Matches", stat3: 0, stat3_label: "Avg", prev_team: "Domestic", status: "pending" },
  { id: 101, name: "Sameer Rizvi", role: "Batsman", country: "India", base_price: 0.75, age: 21, stat1: 80, stat1_label: "Rating", stat2: 0, stat2_label: "Matches", stat3: 0, stat3_label: "Avg", prev_team: "CSK", status: "pending" },
  { id: 102, name: "Nehal Wadhera", role: "Batsman", country: "India", base_price: 0.75, age: 24, stat1: 82, stat1_label: "Rating", stat2: 14, stat2_label: "Matches", stat3: 26.6, stat3_label: "Avg", prev_team: "MI", status: "pending" },
  { id: 103, name: "Nishant Sindhu", role: "All-rounder", country: "India", base_price: 0.75, age: 20, stat1: 81, stat1_label: "Rating", stat2: 0, stat2_label: "Matches", stat3: 0, stat3_label: "Avg", prev_team: "CSK", status: "pending" },
  { id: 104, name: "Angkrish Raghuvanshi", role: "Batsman", country: "India", base_price: 0.75, age: 19, stat1: 80, stat1_label: "Rating", stat2: 0, stat2_label: "Matches", stat3: 0, stat3_label: "Avg", prev_team: "KKR", status: "pending" },
  { id: 105, name: "Harpreet Brar", role: "Bowler", country: "India", base_price: 0.75, age: 29, stat1: 85, stat1_label: "Rating", stat2: 28, stat2_label: "Matches", stat3: 7.12, stat3_label: "Economy", prev_team: "PBKS", status: "pending" },
  { id: 106, name: "Mayank Markande", role: "Bowler", country: "India", base_price: 0.75, age: 27, stat1: 86, stat1_label: "Rating", stat2: 20, stat2_label: "Matches", stat3: 8.52, stat3_label: "Economy", prev_team: "SRH", status: "pending" },
  { id: 107, name: "Suyash Sharma", role: "Bowler", country: "India", base_price: 0.75, age: 21, stat1: 84, stat1_label: "Rating", stat2: 11, stat2_label: "Matches", stat3: 8.23, stat3_label: "Economy", prev_team: "KKR", status: "pending" },
  { id: 108, name: "Venkatesh Iyer", role: "All-rounder", country: "India", base_price: 0.75, age: 30, stat1: 92, stat1_label: "Rating", stat2: 36, stat2_label: "Matches", stat3: 28.1, stat3_label: "Avg", prev_team: "KKR", status: "pending" },
  { id: 109, name: "Ruturaj Hangargekar", role: "Bowler", country: "India", base_price: 0.75, age: 22, stat1: 83, stat1_label: "Rating", stat2: 2, stat2_label: "Matches", stat3: 10.0, stat3_label: "Economy", prev_team: "CSK", status: "pending" },
  { id: 110, name: "Yash Thakur", role: "Bowler", country: "India", base_price: 0.75, age: 26, stat1: 82, stat1_label: "Rating", stat2: 9, stat2_label: "Matches", stat3: 9.15, stat3_label: "Economy", prev_team: "LSG", status: "pending" },

  // Overseas (111-130) - 1.50 Cr & 1.00 Cr
  { id: 111, name: "David Miller", role: "Batsman", country: "SA", base_price: 1.50, age: 35, stat1: 93, stat1_label: "Rating", stat2: 121, stat2_label: "Matches", stat3: 36.1, stat3_label: "Avg", prev_team: "GT", status: "pending" },
  { id: 112, name: "Steve Smith", role: "Batsman", country: "Australia", base_price: 1.50, age: 35, stat1: 93, stat1_label: "Rating", stat2: 103, stat2_label: "Matches", stat3: 34.5, stat3_label: "Avg", prev_team: "DC", status: "pending" },
  { id: 113, name: "Harry Brook", role: "Batsman", country: "England", base_price: 1.50, age: 26, stat1: 93, stat1_label: "Rating", stat2: 11, stat2_label: "Matches", stat3: 21.0, stat3_label: "Avg", prev_team: "DC", status: "pending" },
  { id: 114, name: "Wanindu Hasaranga", role: "All-rounder", country: "SL", base_price: 1.50, age: 27, stat1: 93, stat1_label: "Rating", stat2: 26, stat2_label: "Matches", stat3: 8.13, stat3_label: "Economy", prev_team: "SRH", status: "pending" },
  { id: 115, name: "Lockie Ferguson", role: "Bowler", country: "NZ", base_price: 1.50, age: 33, stat1: 92, stat1_label: "Rating", stat2: 38, stat2_label: "Matches", stat3: 8.66, stat3_label: "Economy", prev_team: "RCB", status: "pending" },
  { id: 116, name: "Daryl Mitchell", role: "All-rounder", country: "NZ", base_price: 1.50, age: 33, stat1: 92, stat1_label: "Rating", stat2: 2, stat2_label: "Matches", stat3: 16.5, stat3_label: "Avg", prev_team: "CSK", status: "pending" },
  { id: 117, name: "Shimron Hetmyer", role: "Batsman", country: "WI", base_price: 1.50, age: 28, stat1: 92, stat1_label: "Rating", stat2: 60, stat2_label: "Matches", stat3: 30.2, stat3_label: "Avg", prev_team: "RR", status: "pending" },
  { id: 118, name: "Alex Hales", role: "Batsman", country: "England", base_price: 1.50, age: 36, stat1: 91, stat1_label: "Rating", stat2: 6, stat2_label: "Matches", stat3: 24.1, stat3_label: "Avg", prev_team: "KKR", status: "pending" },
  { id: 119, name: "Finn Allen", role: "Batsman", country: "NZ", base_price: 1.50, age: 25, stat1: 91, stat1_label: "Rating", stat2: 0, stat2_label: "Matches", stat3: 0, stat3_label: "Avg", prev_team: "RCB", status: "pending" },
  { id: 120, name: "Josh Inglis", role: "Wicketkeeper", country: "Australia", base_price: 1.50, age: 29, stat1: 90, stat1_label: "Rating", stat2: 0, stat2_label: "Matches", stat3: 0, stat3_label: "Avg", prev_team: "Overseas", status: "pending" },
  { id: 121, name: "Jason Roy", role: "Batsman", country: "England", base_price: 1.00, age: 34, stat1: 90, stat1_label: "Rating", stat2: 13, stat2_label: "Matches", stat3: 32.1, stat3_label: "Avg", prev_team: "KKR", status: "pending" },
  { id: 122, name: "Dawid Malan", role: "Batsman", country: "England", base_price: 1.00, age: 37, stat1: 92, stat1_label: "Rating", stat2: 1, stat2_label: "Matches", stat3: 26.0, stat3_label: "Avg", prev_team: "PBKS", status: "pending" },
  { id: 123, name: "Rovman Powell", role: "All-rounder", country: "WI", base_price: 1.00, age: 31, stat1: 90, stat1_label: "Rating", stat2: 17, stat2_label: "Matches", stat3: 19.8, stat3_label: "Avg", prev_team: "RR", status: "pending" },
  { id: 124, name: "Kusal Perera", role: "Wicketkeeper", country: "SL", base_price: 1.00, age: 34, stat1: 89, stat1_label: "Rating", stat2: 0, stat2_label: "Matches", stat3: 0, stat3_label: "Avg", prev_team: "Overseas", status: "pending" },
  { id: 125, name: "Pathum Nissanka", role: "Batsman", country: "SL", base_price: 1.00, age: 26, stat1: 90, stat1_label: "Rating", stat2: 0, stat2_label: "Matches", stat3: 0, stat3_label: "Avg", prev_team: "Overseas", status: "pending" },
  { id: 126, name: "Dasun Shanaka", role: "All-rounder", country: "SL", base_price: 1.00, age: 33, stat1: 91, stat1_label: "Rating", stat2: 3, stat2_label: "Matches", stat3: 6.67, stat3_label: "Avg", prev_team: "GT", status: "pending" },
  { id: 127, name: "James Neesham", role: "All-rounder", country: "NZ", base_price: 1.00, age: 34, stat1: 90, stat1_label: "Rating", stat2: 14, stat2_label: "Matches", stat3: 8.5, stat3_label: "Avg", prev_team: "RR", status: "pending" },
  { id: 128, name: "Shai Hope", role: "Wicketkeeper", country: "WI", base_price: 1.00, age: 31, stat1: 90, stat1_label: "Rating", stat2: 0, stat2_label: "Matches", stat3: 0, stat3_label: "Avg", prev_team: "DC", status: "pending" },
  { id: 129, name: "Brandon King", role: "Batsman", country: "WI", base_price: 1.00, age: 30, stat1: 89, stat1_label: "Rating", stat2: 0, stat2_label: "Matches", stat3: 0, stat3_label: "Avg", prev_team: "Overseas", status: "pending" },
  { id: 130, name: "Matthew Wade", role: "Wicketkeeper", country: "Australia", base_price: 1.00, age: 37, stat1: 88, stat1_label: "Rating", stat2: 13, stat2_label: "Matches", stat3: 15.6, stat3_label: "Avg", prev_team: "GT", status: "pending" },
];

const teams = [
  { id: 1, code: 'MI',   name: 'Mumbai Indians',            purse: 100.00, players_bought: 0, total_spent: 0 },
  { id: 2, code: 'CSK',  name: 'Chennai Super Kings',       purse: 100.00, players_bought: 0, total_spent: 0 },
  { id: 3, code: 'RCB',  name: 'Royal Challengers Bengaluru', purse: 100.00, players_bought: 0, total_spent: 0 },
  { id: 4, code: 'KKR',  name: 'Kolkata Knight Riders',     purse: 100.00, players_bought: 0, total_spent: 0 },
  { id: 5, code: 'DC',   name: 'Delhi Capitals',            purse: 100.00, players_bought: 0, total_spent: 0 },
  { id: 6, code: 'RR',   name: 'Rajasthan Royals',          purse: 100.00, players_bought: 0, total_spent: 0 },
  { id: 7, code: 'PBKS', name: 'Punjab Kings',              purse: 100.00, players_bought: 0, total_spent: 0 },
  { id: 8, code: 'SRH',  name: 'Sunrisers Hyderabad',       purse: 100.00, players_bought: 0, total_spent: 0 },
  { id: 9, code: 'GT',   name: 'Gujarat Titans',            purse: 100.00, players_bought: 0, total_spent: 0 },
  { id:10, code: 'LSG',  name: 'Lucknow Super Giants',      purse: 100.00, players_bought: 0, total_spent: 0 },
];

const auction = {
  status: 'waiting',
  current_player_id: null,
  current_bid: 0,
  leading_team_code: null,
  leading_team_name: null,
  bid_count: 0,
  timer_seconds: 160,
};

const bids = [];
const squads = {};

module.exports = { players, teams, auction, bids, squads };
